default:
    pattern:  /
    defaults: { _controller: "WappAdministradorBundle:Default:index" }
administrador_default_login_error:
    pattern:  /loginError
    defaults: { _controller: "WappAdministradorBundle:Default:loginError" }
administrador_default_login:
    pattern:  /login
    defaults: { _controller: "WappAdministradorBundle:Default:login" }
administrador_default_login_check:
    pattern: /login_check
administrador_default_logout:
    pattern: /logout
    defaults: { _controller: "WappAdministradorBundle:Default:logout" }