parameters:
  administrador.login_success_handler.class: Wapp\AdministradorBundle\Listener\LoginListener
services:
#    wapp_administrador.example:
#        class: Wapp\AdministradorBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
  administrador.login_success_handler.class:
    class: %administrador.login_success_handler.class%
    public: false
    arguments:  ['@service_container']